바텀 시트 컴포넌트 추가
SOPTerest/Client pull request #17
Opened 2022-05-25 05:43 UTC by aeuna

## ⛓ Related Issues
- close #8

## 📋 작업 내용
- [x] 바텀 시트 컴포넌트 추가
- [x] 피그마 스타일 가이드 변경사항 font 사이즈 및 line-height 변경 

## 📌 PR Point
- MyPage에서 ```const [open, setOpen] = useState(false);``` 선언해서 
setOpen을  전달해서 모달을 보여줄려고 합니다. 이런 방식으로 해도 괜찮을 까요?
- 컨벤션도 맞는지 봐주시면 감사하겠습니다!
- 버튼 svg 추가 하기 위해서 assets/buttons 폴더 만들어서 아래에 넣었습니다!

## 👀 스크린샷 / GIF / 링
<img width="361" alt="스크린샷 2022-05-25 오후 1 39 23" src="https://user-images.githubusercontent.com/42725903/170187270-55df4964-3f60-42eb-ae56-d7a8298f45c2.png">

https://user-images.githubusercontent.com/42725903/170187371-13d651ab-6f26-4980-8b8f-12608b12df35.mov

2022-05-25 07:16 UTC, leeseooo requested changes
아 conflict가 난 이유가 main의 가장 최신 pull을 은아언니 branch에서 가지고 있지 않아서 그런 것 같네요!?

2022-05-25 07:16 UTC, leeseooo commented on src/assets/buttons/index.ts
> +export { ReactComponent as BtClose } from './btn_close.svg';
닫기 버튼을 button 태그로 만들어보는 건 어떨까요? 
이미지나 아이콘만 svg로 불러오면 될 것 같다고 생각해요

2022-05-25 07:16 UTC, leeseooo commented on src/components/BottomSheet.tsx
> +export default function BottomSheet({ onToggleModal }: any) {
```suggestion
interface BottomSheetProps{
  onToggleModal : () => void;
}
export default function BottomSheet({ onToggleModal }: BottomSheetProps) {
```
저도 공부한 지 얼마 안 돼서 잘 모르겠지만 interface나 type으로 props 형태를 지정해주면 되려나? @NamJwong  도와주세요 ㅎㅎ!!

2022-05-25 16:03 UTC, NamJwong requested changes
> MyPage에서 const [open, setOpen] = useState(false); 선언해서
setOpen을 전달해서 모달을 보여줄려고 합니다. 이런 방식으로 해도 괜찮을 까요?

너무 좋아요~

> set 함수를 props로 전달해주게되면 타입을 보통 뭐로 지정을 하나요..? 일단 Any로 지정했습니다
https://jemerald.tistory.com/127 참고해봤는데 빨간줄이 뜨더라고요!

set 함수 자체를 넘기는 거에 대한 우려는 설명해줬구 그래도 넘길 일이 있다면 그냥 `(newState: state타입) => void` 이렇게 해주면 돼요

> 컨벤션도 맞는지 봐주시면 감사하겠습니다!

굳굳입니다~

> 버튼 svg 추가 하기 위해서 assets/buttons 폴더 만들어서 아래에 넣었습니다!

요런 것은 svg로 가져오지 않고 직접 구현을 하셔야 해요~~

2022-05-25 16:03 UTC, NamJwong commented on src/assets/buttons/index.ts
> +export { ReactComponent as BtClose } from './btn_close.svg';
동의합니다 웬만하면 svg로 안해도 되는건 안하는게 좋습니다! 무거워저영 이것은 직접 구현해주세요!

2022-05-25 16:03 UTC, NamJwong commented on src/components/BottomSheet.tsx
> +export default function BottomSheet({ onToggleModal }: any) {
저렇게 하면 됩니다!!!!!!!!!!! 굳굳굳

2022-05-25 16:03 UTC, NamJwong commented on src/components/BottomSheet.tsx
> +        </StButtonFormatWrapper>
이 버튼은 왜 래퍼로 하나 감쌌어요??

2022-05-27 01:19 UTC, aeuna reviewed
pr 반영 했습니다!
- 함수 타입 인터페이스로 만들어서 타입 지정
- svg 지우고, 버튼 태그 만들기

2022-05-27 01:19 UTC, aeuna commented on src/assets/buttons/index.ts
> +export { ReactComponent as BtClose } from './btn_close.svg';
아하 좋습니다!! 👍

2022-05-27 01:19 UTC, aeuna commented on src/components/BottomSheet.tsx
> +        </StButtonFormatWrapper>
화면 너비가 넓어지면 **버튼**이랑 **프로필에 추가**가 가운데에 위치하게 하고 싶어서 감쌌습니다!
아 스타일드 컴포넌트 명도 바꿔야 겠네요!

2022-05-27 01:19 UTC, aeuna commented on src/components/BottomSheet.tsx
> +export default function BottomSheet({ onToggleModal }: any) {
아하 좋습니다!! 👍

2022-05-27 05:16 UTC, leeseooo approved these changes
👍짱👍짱👍

2022-05-27 05:16 UTC, leeseooo commented on src/components/BottomSheet.tsx
> +  background-color: #efefef;
```suggestion
  background-color: ${COLOR.GRAY_300}
```
이거 컬러 상수 이용해서 작성해주시면 더 좋을 것 같아요!

2022-05-27 11:29 UTC, NamJwong approved these changes

2022-05-27 11:29 UTC, merged