디자인 시스템 세팅하기 #2
SOPTerest/Client pull request #3
Opened 2022-05-16 05:43 UTC by leeseooo

## ⛓ Related Issues
- close #2

## 📋 작업 내용
- [x] ~ font 및 color 세팅

## 📌 PR Point
- 너가소개서 깃헙을 참고해서 `font.ts`를 작성해봤어요. 
`Font` interface에 `size`, `weight`, `type` 으로 정해준 게 적절한지 확인해주세요!

- 서브셋 폰트를 못 찾아서 서브셋 폰트 메이커를 이용해보려고 시도했지만 잘 안 됐습니다 !🥲 
폰트 깃헙에서 @font-face를 적용하는 방법을 발견해서 `font.css` 파일에 적용해주었는데, 
해당 css 파일을 `font.ts`에서 import해주지 않아도 적용이 되는걸까요?

- 근데 지금 Figma 확인해보니까 AppleSDGothicNeoB00 인데 웹폰트도 없고 그냥 다운로드 받아야 하는 것 같아서
(https://github.com/adrinerDP/font-applesdgothicneo)](https://github.com/adrinerDP/font-applesdgothicneo) 에서 
AppleSDGothicNeo - Bold와 Regular를 @font-face에 작성했거든요... 이게 같은 굵기의 폰트인지 확인해봐야겠죠??

## 👀 스크린샷 / GIF / 링크

## 🔬 Reference

2022-05-16 10:05 UTC, NamJwong requested changes
디자너님이 주신 폰트 파일 보니까 그냥 피그마에서 B00이렇게 보이는건 Bold 폰트여서 그런 것 같고 지금 한 것처럼 Bold Regular font-weight 잘 나눠주면 될 것 같습니다! 👍

2022-05-16 10:05 UTC, NamJwong commented on src/styles/color.ts
> +    GREY_3: 'EFEFEF',
GRAY로 바꿔주세요!

그리고 숫자가 붙는 이런 상수는 100단위 이상으로 해주면 좋아요! 숫자 사이의 값이 새로 생길 수 있어서 그런데 예를 들어 프로젝트를 진행하다 디자이너가 gray1.5라는 컬러를 추가할 수도 있어요 지금 실제로 추가적으로 뷰가 나올 상황이기도 하니까 수정하면 좋을 것 같아요!

```suggestion
    GRAY_100: '767676',
    GRAY_200: 'CDCDCD',
    GRAY_300: 'EFEFEF',
```

2022-05-16 10:05 UTC, NamJwong commented on src/styles/fonts/font.ts
> +export const FONT_STYLES = {
H1_BOLD가 빠진 것 같습니다!

2022-05-16 10:05 UTC, NamJwong commented on public/index.html
> +      href="//cdn.jsdelivr.net/npm/font-applesdgothicneo@1.0/all.min.css"
```suggestion
      href="https://cdn.jsdelivr.net/npm/font-applesdgothicneo@1.0.3/css/all.css"
```
이걸로 넣어주셔야 폰트 적용됩니다!

2022-05-16 10:05 UTC, NamJwong commented on src/styles/fonts/font.css
> +@font-face {
이 파일은 필요 없습니다! index.html에 불러왔으니까요!

2022-05-16 10:05 UTC, NamJwong commented on src/styles/fonts/font.ts
> +  font-family: "AppleSDGothicNeo", "Noto Sans KR", sans-serif;
`"Noto Sans KR", sans-serif`은 왜 추가해주셨나요??

2022-05-16 10:41 UTC, aeuna requested changes
피그마에서 변동이 일어나는 것 같아서 반영하기에 어려움이 있는 것 같습니다!! 
디자인 시스템 세팅은 잘 하셨어요 👍

2022-05-16 10:41 UTC, aeuna commented on public/index.html
> +      href="//cdn.jsdelivr.net/npm/font-applesdgothicneo@1.0/all.min.css"
```type="text/css"``` 타입을 써주지 않은 이유가 있나요??

<link>태그의 type 속성은 링크된 외부 리소스의 미디어 타입을 명시한다고 합니당 <br/>
 href속성이 설정되어 있어야 사용할 수 있다고 하네요!! <br/>
https://junbucks7.tistory.com/7
 <br/> <br/>
아! 찾아보니 HTML5에서는 일반적으로 css 지원을 하기 때문에 type 속성이 필요하지 않다고 하네여! <br/>

2022-05-16 10:41 UTC, aeuna commented on src/styles/fonts/font.ts
> +      return 500;
400으로 변경해주어야 할 것 같아요!
디자인팀에서 폰트 weight를 400으로 설정해둔것 같습니다!
<img width="219" alt="스크린샷 2022-05-16 오후 7 37 37" src="https://user-images.githubusercontent.com/42725903/168575242-ee2a3227-1fca-412d-8672-e82c93a9df26.png">

2022-05-16 10:41 UTC, aeuna commented on src/styles/fonts/font.ts
> +  H3_BOLD: FONT({ size: 36, weight: "B", type: "h3" }),
H3부분이 피그마에서 없어진 것 같습니다!

2022-05-16 11:54 UTC, NamJwong commented on src/styles/fonts/font.ts
> +      return 500;
@aeuna 폰트 B인게 weight 700이고 R이 500입니다! weight값이 이미 적용돼있는 폰트를 쓰냐 마냐 차이인데 저희는 한 폰트로 이렇게 쓰면 더 편할 것 같아요!

2022-05-16 11:59 UTC, leeseooo commented on src/styles/fonts/font.ts
> +  font-family: "AppleSDGothicNeo", "Noto Sans KR", sans-serif;
어랏 그러게요 가져오다가 까먹고 안 지웠습니다..😓

2022-05-16 12:06 UTC, leeseooo commented on src/styles/fonts/font.ts
> +      return 500;
Bold 폰트 자체의 font-weight가 500이라서 500으로 해줬습니다!

2022-05-16 12:09 UTC, leeseooo commented on src/styles/fonts/font.ts
> +  H3_BOLD: FONT({ size: 36, weight: "B", type: "h3" }),
다시 확인해봤는데 PinEdit 뷰의 보드 타이틀에 있습니다! 함 확인해주세요😶

2022-05-16 12:11 UTC, leeseooo commented on src/styles/fonts/font.ts
> +export const FONT_STYLES = {
꼼꼼하지 못했군요...제성함다

2022-05-16 12:14 UTC, merged

2022-05-29 12:22 UTC, joohaem commented
LGTM🔥🔥🔥🔥
theme 설정 멋져서 참고하겠습니다🙏

2022-05-29 12:24 UTC, NamJwong commented
> LGTM🔥🔥🔥🔥 theme 설정 멋져서 참고하겠습니다🙏

@김서진 영향력 최고셔여