공통 Pin List 컴포넌트 구현
SOPTerest/Client pull request #7
Opened 2022-05-18 05:05 UTC by leeseooo

## ⛓ Related Issues
- close #6

## 📋 작업 내용
- [x] ~ CommonPinList.tsx 컴포넌트 및 pin.ts 타입 생성

## 📌 PR Point
### 무슨 이유로 어떻게 코드를 변경했는지
1. props를 넘겨주기 위해 메인페이지인 Pin.tsx에 Pin 정보를 담고 있는 배열 하나를 만들었습니다.
2. pin.ts에 타입을 대략적으로 작성해봤습니다.
`id` : 각각의 Pin마다 고유 id가 필수로 있어야할 것 같아서 만들었습니다.
`pin_img` : Pin image를 string으로 받기 위해 썼습니다.

🔻 이하 속성들은 존재하는 뷰도 있고 존재하지 않는 뷰도 있어서 option으로 줬습니다.
![image](https://user-images.githubusercontent.com/66051416/168959661-dbc0c9d4-0f31-4561-979e-73905a7a6bf6.png)

`title?` : Figma에 새로 생긴 mypage 뷰 보니까 위에 첨부한 사진 UI가 있어서 이것도 공통 컴포넌트로 포함시켜야 할까 고민했어요. 사진의 board 컴포넌트의 '바닷가' 타이틀 텍스트를 위한 속성으로 줬습니다.
`profile_img?` : 프로필 이미지가 있는 뷰도 있고 없는 뷰도 있어서 option으로 줬습니다.
`nickname?` : 유저 네임입니다.
`pin?` : 이것도 title이랑 같은 맥락에서 핀 개수를 정해주려고 만들었습니다. 근데 저 board를 따로 뺀다면 title, pin, saved_time은 필수적인 속성이니까 물음표를 빼야겠네요
`saved_time?` : 위 사진에서 '방금' 이라는 텍스트를 위해 Pin 저장시간을 Date로 저장한 후, 현재 시간과 비교해서 텍스트를 보여주려고 만들었습니다.

---

### 어떤 부분에 리뷰어가 집중해야 하는지
1.  **Figma 좌측상단의 style guide에 있는 board 컴포넌트를 제가 만든 CommonPinList.tsx에서 공통으로 처리해줘야 할지, 아니면 따로 만들어야할 지** 잘 모르겠습니다! 근데 저는 따로 만드는 게 좋을 것 같긴 한데요... 의견 주시면 감사하겠습니다!!
2. 타입 추론?이 적절한 지 봐주세요!! 처음이라 어색하네요😓🥲🥲

## 👀 스크린샷 / GIF / 링크

## 🔬 Reference

2022-05-18 05:36 UTC, NamJwong reviewed
디자인이 바뀐 부분이라,, 일단 컨벤션 위주랑 안바뀔 부분에다 리뷰 달았습니다!

2022-05-18 05:36 UTC, NamJwong commented on src/components/CommonPinList.tsx
> +}
저희 props 인터페이스는 아래 형태가 컨벤션입니다!
```ts
interface 컴포넌트명Props {
}
```

2022-05-18 05:36 UTC, NamJwong commented on src/components/CommonPinList.tsx
> +    <StPinWrapper>
컴포넌트 가장 바깥 스컴포넌트는 `StWrapper` 이걸로 고정하기로 했어요!

2022-05-18 05:36 UTC, NamJwong commented on src/components/CommonPinList.tsx
> +      <StPinLists>
그냥 StPinList라고 하면 될 것 같아요~

2022-05-18 05:36 UTC, NamJwong commented on src/components/CommonPinList.tsx
> +              </>
PinItem이라는 컴포넌트로 따로 빼는게 나을 것 같아요~

2022-05-18 08:21 UTC, leeseooo commented on src/components/CommonPinList.tsx
> +}
앗 넵!

2022-05-18 08:21 UTC, leeseooo commented on src/components/CommonPinList.tsx
> +    <StPinWrapper>
넵 수정할게요!

2022-05-18 16:22 UTC, aeuna requested changes
타입은 다시 생긴 뷰 보면서 같이 이야기 해도 좋을 것 같습니다!!
board 컴포넌트는 뭔가 아래 뷰들을 사용하지 않을 것 같아서 CommonPinList가 변도되지 않을까 싶네여,,ㅠㅠㅠ

2022-05-18 16:22 UTC, aeuna commented on src/components/CommonPinList.tsx
> +          if (pin.id < pinList.length / 2) {
pinList 안에서 map 돌때, pin.id < pinList.length/2 이렇게 길이랑 아이디를 비교한 이유가 있나요??
나중에 서버 이용해서 데이터 받아올 때, state 사용해서 Pin 컴포넌트에서 CommmonPinList 컴포넌트를 부를때,
state가 null 이 아닌 조건이나 혹은 배열의 길이가 0 이상 조건을 따져서 보여주면 좋을 것 같아요!

2022-05-18 16:22 UTC, aeuna commented on src/components/CommonPinList.tsx
> +                  <StPinImage src={pin.pin_img} />
alt 속성도 적어주면 좋을 것 같습니다!
alt 속성은 사용자가 느린 네트워크 환경이나 src 속성값의 오류, 시각 장애인용 스크린 리더의 사용 등 어떤 이유로든 사용자가 이미지를 볼 수 없을 때 이미지 대신 제공할 대체 정보를 제공한다고 해요!

2022-05-18 16:22 UTC, aeuna commented on src/components/CommonPinList.tsx
> +const FlexColumnWrapper = styled.div`
오 이렇게 사용하니 좋네여!! 👍

2022-05-18 16:48 UTC, NamJwong commented on src/components/CommonPinList.tsx
> +          if (pin.id < pinList.length / 2) {
요건 배열을 두줄로 왼오왼오 나눠서 쓰려던 것 같은데 근데 생각해보니 한배열로도 flex로 어떻게 해볼 수 있을 것 같아여 그른데 이제 바뀐 뷰에서는 나눌 필요가 없어서 ~~,,

2022-05-19 01:28 UTC, leeseooo commented on src/components/CommonPinList.tsx
> +          if (pin.id < pinList.length / 2) {
아 생각해보니 꼭 두 줄로 안하고 한줄에서 길이만 맞추면 자동으로 내려갔겠네요

2022-05-19 01:29 UTC, leeseooo commented on src/components/CommonPinList.tsx
> +                  <StPinImage src={pin.pin_img} />
아앗 alt를 빠뜨리다니

2022-05-19 14:46 UTC, NamJwong requested changes
작업 속도 대박입니다👍👍👍 고생하셨습니다! 리뷰 몇 가지 확인해주세요🫶

이런 퍼블리싱이 포함된 PR은 웬만하면 스크린샷을 올려주세요!
코드만 보고 리뷰하기 어려울 수 있습니다~

2022-05-19 14:46 UTC, NamJwong commented on src/components/PinBoard.tsx
> +interface PinBoardProps {
전반적으로 명칭 PinBoard 말고 그냥 Board라고 해야 할 것 같아요 왜냠 그냥 '보드' 자체가 명칭이고 그 안에 '핀'이 있는거여서!

2022-05-19 14:46 UTC, NamJwong commented on src/components/PinBoard.tsx
> +export default function PinBoard({ pinBoardList }: PinBoardProps) {
컴포넌트명 BoardList가 적당할 것 같아요 말그대로 보드들의 리스트니까!

2022-05-19 14:46 UTC, NamJwong commented on src/components/PinBoard.tsx
> +        <PinItem pin={pin} key={idx} />
네이밍 BoardItem이 맞는 말 같습니다!

2022-05-19 14:46 UTC, NamJwong commented on src/components/PinBoard.tsx
> +        <PinItem pin={pin} key={idx} />
index를 key 값으로 주시면 안됩니다! 타입에 id를 추가하고 id를 key로 사용해주세요~

https://ko.reactjs.org/docs/lists-and-keys.html#keys

2022-05-19 14:46 UTC, NamJwong commented on src/types/pin.ts
> +}
너무 좋아요! id 값만 추가해주시고 BoardItem 엘리먼트 리스트 만들 때 key 값으로 써주세요 서버에서 id 값 분명 줄거예요!

2022-05-19 14:46 UTC, NamJwong commented on src/types/pin.ts
> +}
여기 파일명 그냥 index.ts로 해도 좋을 것 같아요! 우리 프로젝트 전체적으로 필요한 타입이 몇 개 없을 것 같고 pin이라는 분류 자체도 애매해서요! pin은 우리 뷰 전반적으로 다 관련 있으니까요~

2022-05-19 14:46 UTC, NamJwong commented on src/styles/color.ts
> +  WHITE: '#FFFFFF',
👍👍👍

2022-05-19 14:46 UTC, NamJwong commented on src/types/pin.ts
> +}
BoardPinInfo 라고 해서 보드 전용 핀 타입으로 명시되게 네이밍 하면 좋겠구 이것도 id 값만 추가해주세요!

2022-05-19 14:46 UTC, NamJwong commented on src/components/PinItem.tsx
> +                <StPinImage src={pinItem.pin_img} key={idx} />
여기도 key로 id값 사용해주세요!

2022-05-19 14:50 UTC, leeseooo commented on src/components/PinBoard.tsx
> +interface PinBoardProps {
아하아하 네넵!!

2022-05-19 14:53 UTC, NamJwong commented on src/components/PinItem.tsx
> +    `}
3분할 된 핀들의 너비를 px말고 %로 해야 하지 않을까 고민되네요.. 왜냐하면 지금 피그마에서 지정된 기본 전체 너비보다 좁은 환경에서는 깨지게 되거든요 웬만하면 전체를 꽉 채우는 너비는 고정적인 값 말고 비율로 해서 반응형이 되게 해야 해요 그런데 이거는 그렇게 하려면 임의로 비율을 설정해야 하는데 디자너분들과 상의하는게 좋을지.. 어렵네요 어떻게 생각하시나요! @leeseooo @aeuna

2022-05-19 14:57 UTC, leeseooo commented on src/types/pin.ts
> +}
오...네 알겠슴닷 이런 부분이 아직 낯설고 어렵네요!!

2022-05-19 14:57 UTC, leeseooo commented on src/styles/color.ts
> +  WHITE: '#FFFFFF',
히히

2022-05-19 15:04 UTC, leeseooo commented on src/components/PinItem.tsx
> +    `}
개발자 도구에서 모바일 환경으로 보는 거로는 혹시 의미가 없을까요? 확인해보면 비율 그대로 줄어들긴 하던데 제가 %로 안줬으니까 이렇게 보는 건 아닌 것 같군여 ㅎ.ㅎ;
저는...잘 모르겠지만 ...디쟌분들과 상의해봐도 좋을 것 같아요

2022-05-19 17:06 UTC, NamJwong approved these changes
빠른 반영 최고😍👍👍👍 아까 몇개 놓쳐서 추가로 확인해주시면 감사하겠습니다~!

2022-05-19 17:06 UTC, NamJwong commented on src/components/BoardItem.tsx
> +const StImageWrapper = styled.div<PinImageProps>`
요 PinImageProps는 스컴포넌트만을 위한거니 굳이 위에 따로 선언해줄 필요 없이 이렇게 해줘도 될 것 같아요~~
```suggestion
const StImageWrapper = styled.div<{ idx: number }>`
```

2022-05-19 17:06 UTC, NamJwong commented on src/pages/Pin.tsx
>  export default function Pin() {
여기는 MyPage라고 하는게 더 맞는 것 같습니다!!
<img width="234" alt="image" src="https://user-images.githubusercontent.com/73823388/169355137-8803831f-0f6a-4846-bf49-f9172e7307b3.png">

2022-05-19 17:06 UTC, NamJwong commented on src/components/PinItem.tsx
> +    `}
지금 보면 전체 너비가 피그마보다 더 넓을 때는 공간이 남는 문제도 있어서 제가 디자너님들한테 한번 물어볼게요!
<img width="354" alt="image" src="https://user-images.githubusercontent.com/73823388/169357252-f84d9b91-7e28-4f41-b90e-4011f6c1b515.png">

2022-05-19 17:06 UTC, NamJwong commented on src/components/BoardItem.tsx
> +const StImageWrapper = styled.div<PinImageProps>`
만약 지금 형태를 유지한다면 컴포넌트명+Props가 컨벤션이니 StImageWrapperProps가 맞는데 저는 그냥 위 형태로 해줘도 될 것 같습니다!

2022-05-19 17:06 UTC, NamJwong commented on src/pages/Pin.tsx
>  export default function Pin() {
라우팅 때문에 임시로 이렇게 해줬군요!!! 이거 머지하고 라우팅 새로 합시다!

2022-05-19 17:10 UTC, NamJwong commented on src/components/PinItem.tsx
> +    `}
전체 너비가 좁아지는 경우에는 문제 없는거 맞네요👍

2022-05-19 17:17 UTC, aeuna reviewed
크 빠르시네여 👍 💯

2022-05-19 17:17 UTC, aeuna commented on src/types/index.ts
> +  pinImg: string;
보드를 막 생성한 경우에는 이미지 url이 생성 안되는 경우도 있을 것 같아요! 
약간 저도 고민이 되는데,
- 옵셔널로 선언을 해주거나 혹은 null, undefined 타입들도 써주기
- default 이미지 url로 넣어주는 것으로 대신하기? 
요런 대안들을 생각할 수 있을 것 같아여!

2022-05-19 17:17 UTC, aeuna commented on src/components/BoardItem.tsx
> +            id < 3 && (
이 부분을 배열 슬라이싱해서 보여주는 것도 후보로 생각해보면 좋을 것 같습니다!!
```board.boardList.slice(0,3).map ~~```

2022-05-19 17:38 UTC, NamJwong commented on src/types/index.ts
> +  pinImg: string;
보드를 생성하고 핀 추가 기능이 없기 때문에 pinList가 빈배열이 됩니다! 빈배열일 경우에 default 이미지 넣어주도록 처리하면 되기 때문에 타입은 안건드려도 될 것 같아요~~

2022-05-19 17:39 UTC, NamJwong commented on src/components/BoardItem.tsx
> +            id < 3 && (
와!! 은아짱이당 좋아요~~ map을 다 돌리지 말고 잘라서 돌리는게 훨씬 좋을 것 같아요!

2022-05-20 02:03 UTC, leeseooo commented on src/components/PinItem.tsx
> +    `}
아아 grid를 써서 그런걸수도 있겠네요 
네 확인했습니다!!!👍👍👍

2022-05-20 02:07 UTC, leeseooo commented on src/types/index.ts
> +  pinImg: string;
아아 이해했습니다! 막 생성 시 이미지 처리를 생각을 못했네요😯

2022-05-20 02:08 UTC, leeseooo commented on src/components/BoardItem.tsx
> +            id < 3 && (
혹시 하버드생이신가요?

2022-05-20 06:16 UTC, aeuna commented on src/components/PinItem.tsx
> +    `}
%로 주면 확실히 전체 너비 변동이 있어도 변형이 있게 되지는 않으니 디팀과 상의 부탁드려도 좋을 것 같습니다!

2022-05-20 06:19 UTC, aeuna approved these changes
전반적으로 좋습니다! 컴포넌트 만들때 코드를 참고해야겠어요!

2022-05-20 06:22 UTC, merged